### PR TITLE
Use circle as image for changed state

### PR DESCRIPTION
**Pull request by florianpircher**
Previously it was difficult to tell the added and the changed image apart, especially when scrolling through source code. The circle is similar to the red traffic light of a Cocoa window containing a modified document.

Updated image:

bildschirmfoto 2016-05-30 um 22 16 23

### CODE REVIEW

**Comment by sorbits** [comment]
I agree with the sentiment (that the previous images can be hard to distinguish) and there is precedence for using bullets to indicate “changed” on OS X, however, having run with this change for about a week, I think the visual weight is too high.

Making them too small though I fear they can be confused with the dots used to indicate soft wrap.

Any thoughts on this? Perhaps make them a dash?

**Comment by florianpircher** [comment]
Maybe shrinking the circle ever so slightly would do the trick… back to the lab!

**Comment by florianpircher** [comment]
Updated Image:

bildschirmfoto 2016-06-08 um 18 34 41

Differences:

15i8m9

**Comment by sorbits** [comment]
Been using it for a while now and gotten quite used to the circles and like them :smile:

Thanks for the updated version, I squashed the two commits and merged as da4f506d5e85ab048d68b0239a73797921244684.

**Pull request closed without merging**
